#ifndef _PLUGINMANAGERVERSION_H
#define _PLUGINMANAGERVERSION_H

#define PLUGINMANAGERVERSION_STRING				"1.4.0.0"
#define PLUGINMANAGERVERSION_RESOURCE			1,4,0,0
#define PLUGINMANAGERVERSION_RESOURCE_STRING	"1, 4, 0, 0"
#define PLUGINMANAGERVERSION_RELEASEDATE        "July 2015"

#endif
