#ifndef _PLUGINMANAGERVERSION_H
#define _PLUGINMANAGERVERSION_H

#define PLUGINMANAGERVERSION_STRING				"1.4.3.0"
#define PLUGINMANAGERVERSION_RESOURCE			1,4,3,0
#define PLUGINMANAGERVERSION_RESOURCE_STRING	"1, 4, 3, 0"
#define PLUGINMANAGERVERSION_RELEASEDATE        "October 2016"

#endif
