#ifndef _PLUGINMANAGERVERSION_H
#define _PLUGINMANAGERVERSION_H

#define PLUGINMANAGERVERSION_STRING				"1.0.2.0"
#define PLUGINMANAGERVERSION_RESOURCE			1,0,2,0
#define PLUGINMANAGERVERSION_RESOURCE_STRING	"1, 0, 2, 0"
#define PLUGINMANAGERVERSION_RELEASEDATE        "December 2011"

#endif
