version: 1.4.12.{build}
image: Visual Studio 2022


environment:
  matrix:
  - PlatformToolset: v143

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug
    - Debug-xml-test

install:
    - git submodule -q update --init
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%PlatformToolset%"=="v143" call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - mkdir NotepadTest\unicode\plugins
    - mkdir NotepadTest\unicode\updater
    - mkdir NotepadTest\x64\plugins
    - mkdir NotepadTest\x64\updater
    - copy paths.props.appveyor paths.props
    - msbuild PluginManager.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-
        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v143") {
            if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
                $PluginManagerZipFileName = "PluginManager_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
                7z a $PluginManagerZipFileName .\NotepadTest\x64\*
            }

            if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
                $PluginManagerZipFileName = "PluginManager_$($env:APPVEYOR_REPO_TAG_NAME)_UNI.zip"
                7z a $PluginManagerZipFileName .\NotepadTest\unicode\*
            }
        }

artifacts:
  - path: PluginManager_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: z5nuqsjm/L3HYsjSkMsVBH8EPAK17v3OOXzZDyp9hWx9J6Ff/gDYtbzWMoUtW0dI
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v143
        configuration: Release

